//@version=5
strategy("Bollinger Bands Strategy with 1:3 RR", overlay=true)

max_quantity = math.floor(strategy.equity / close)

length = 20
multiple = 2.0

sma = ta.sma(close, length)
standard_deviation = multiple * ta.stdev(close, length)
upper = sma + standard_deviation
lower = sma - standard_deviation

plot(sma, "Basis", color=color.orange)
plot(upper, "Upper", color=color.white)
plot(lower, "Lower", color=color.white)

is_bullish_signal = ta.crossover(close, lower)
is_bearish_signal = ta.crossunder(close, upper)

if (is_bullish_signal and strategy.opentrades == 0)
    strategy.entry("Long", strategy.long, max_quantity)
    strategy.exit("exit", from_entry="Long", limit=close*1.03, stop=close*0.99)
else if (is_bearish_signal and strategy.opentrades == 0)
    strategy.entry("Short", strategy.short, max_quantity)
    strategy.exit("exit", from_entry="Short", limit=close*0.97, stop=close*1.01)
  
plot(series=(strategy.position_size > 0) ? strategy.opentrades.entry_price(0)*1.03 : na, color=color.green, style=plot.style_linebr, linewidth=5, title="Take Profit")
plot(series=(strategy.position_size > 0) ? strategy.opentrades.entry_price(0)*0.99 : na, color=color.red, style=plot.style_linebr, linewidth=5, title="Stop Loss")
plot(series=(strategy.position_size < 0) ? strategy.opentrades.entry_price(0)*0.97 : na, color=color.green, style=plot.style_linebr, linewidth=5, title="Take Profit")
plot(series=(strategy.position_size < 0) ? strategy.opentrades.entry_price(0)*1.01 : na, color=color.red, style=plot.style_linebr, linewidth=5, title="Stop Loss")