//@version=5
strategy("Resistance and Support with 1:3 RR", overlay=true)

max_quantity = math.floor(strategy.equity / close)

support = ta.lowest(20)
resistance = ta.highest(20)

plot(resistance, "Resistance", color=color.white)
plot(support, "Support", color=color.white)

is_bullish_signal = ta.crossover(close, support)
is_bearish_signal = ta.crossunder(close, resistance)

if (is_bullish_signal and strategy.opentrades == 0)
    strategy.entry("Long", strategy.long, max_quantity)
    strategy.exit("exit", from_entry="Long", limit=close*1.03, stop=close*0.99)
else if (is_bearish_signal and strategy.opentrades == 0)
    strategy.entry("Short", strategy.short, max_quantity)
    strategy.exit("exit", from_entry="Short", limit=close*0.97, stop=close*1.01)
  
plot(series=(strategy.position_size > 0) ? strategy.opentrades.entry_price(0)*1.03 : na, color=color.green, style=plot.style_linebr, linewidth=5, title="Take Profit")
plot(series=(strategy.position_size > 0) ? strategy.opentrades.entry_price(0)*0.99 : na, color=color.red, style=plot.style_linebr, linewidth=5, title="Stop Loss")
plot(series=(strategy.position_size < 0) ? strategy.opentrades.entry_price(0)*0.97 : na, color=color.green, style=plot.style_linebr, linewidth=5, title="Take Profit")
plot(series=(strategy.position_size < 0) ? strategy.opentrades.entry_price(0)*1.01 : na, color=color.red, style=plot.style_linebr, linewidth=5, title="Stop Loss")