//@version=5
strategy("White Soldiers/Black Crows with 1:3 RR", overlay=true)

max_quantity = math.floor(strategy.equity / close)

is_downtrend = open[5] > close[5] and close[5] > close[4] and open[4] > close[4] and close[4] > close[3] and open[3] > close[3]
is_uptrend = open[5] < close[5] and close[5] < close[4] and open[4] < close[4] and close[4] < close[3] and open[3] < close[3]
first_candle_body_height = math.abs(close[2] - open[2])
second_candle_body_height = math.abs(close[1] - open[1])
current_candle_body_height = math.abs(close - open)

is_white_soldiers = is_downtrend and second_candle_body_height > first_candle_body_height and open[2] < close[2] and open[1] > close[2] and current_candle_body_height >= second_candle_body_height and open[1] < close[1] and close > close[1] and (close[1] >= (high[1] - 0.1)) and (close >= (high - 0.1))
is_black_crows = is_uptrend and second_candle_body_height > first_candle_body_height and open[2] > close[2] and close[1] < close[2] and current_candle_body_height >= second_candle_body_height and open[1] > close[1] and close < close[1] and (close[1] <= (low[1] + 0.1)) and (close <= (low + 0.1))

if (is_white_soldiers and strategy.opentrades == 0)
    strategy.entry("Long", strategy.long, max_quantity)
    strategy.exit("exit", from_entry="Long", limit=close*1.03, stop=close*0.99)
else if (is_black_crows and strategy.opentrades == 0)
    strategy.entry("Short", strategy.short, max_quantity)
    strategy.exit("exit", from_entry="Short", limit=close*0.97, stop=close*1.01)
  
plot(series=(strategy.position_size > 0) ? strategy.opentrades.entry_price(0)*1.03 : na, color=color.green, style=plot.style_linebr, linewidth=5, title="Take Profit")
plot(series=(strategy.position_size > 0) ? strategy.opentrades.entry_price(0)*0.99 : na, color=color.red, style=plot.style_linebr, linewidth=5, title="Stop Loss")
plot(series=(strategy.position_size < 0) ? strategy.opentrades.entry_price(0)*0.97 : na, color=color.green, style=plot.style_linebr, linewidth=5, title="Take Profit")
plot(series=(strategy.position_size < 0) ? strategy.opentrades.entry_price(0)*1.01 : na, color=color.red, style=plot.style_linebr, linewidth=5, title="Stop Loss")